from __future__ import annotations


# native 后端不在 IR 里重写算法，而是 declare + 链接 C 运行时（c_runtime.py 的
# RUNTIME_SOURCE 已分离编译就绪）。下表是用到的运行时函数对应的 LLVM 声明，
# generate() 只发射 used_runtime 里实际登记过的那些。
RUNTIME_SIGNATURES: dict[str, str] = {
    # 字符串
    "sa_strdup": "declare ptr @sa_strdup(ptr)",
    "sa_str_length": "declare i64 @sa_str_length(ptr)",
    "sa_str_concat": "declare ptr @sa_str_concat(ptr, ptr)",
    "sa_str_slice": "declare ptr @sa_str_slice(ptr, i64, i64)",
    "sa_str_find": "declare i64 @sa_str_find(ptr, ptr)",
    "sa_str_upper": "declare ptr @sa_str_upper(ptr)",
    "sa_str_lower": "declare ptr @sa_str_lower(ptr)",
    "sa_str_replace": "declare ptr @sa_str_replace(ptr, ptr, ptr)",
    "sa_net_http_get": "declare ptr @sa_net_http_get(ptr)",
    "sa_net_http_status": "declare i64 @sa_net_http_status(ptr)",
    "sa_net_http_post": "declare ptr @sa_net_http_post(ptr, ptr, ptr)",
    "sa_net_http_request": "declare ptr @sa_net_http_request(ptr, ptr, ptr, ptr)",
    "sa_net_http_request_status": "declare i64 @sa_net_http_request_status(ptr, ptr, ptr, ptr)",
    "sa_net_http_request_timeout": "declare ptr @sa_net_http_request_timeout(ptr, ptr, ptr, ptr, i64)",
    "sa_net_http_request_status_timeout": "declare i64 @sa_net_http_request_status_timeout(ptr, ptr, ptr, ptr, i64)",
    "sa_net_last_headers_copy": "declare ptr @sa_net_last_headers_copy()",
    "sa_net_last_error_copy": "declare ptr @sa_net_last_error_copy()",
    "sa_net_last_code_value": "declare i64 @sa_net_last_code_value()",
    "sa_net_last_peer_host_copy": "declare ptr @sa_net_last_peer_host_copy()",
    "sa_net_last_peer_port_value": "declare i64 @sa_net_last_peer_port_value()",
    "sa_net_urlencode": "declare ptr @sa_net_urlencode(ptr)",
    "sa_net_dns": "declare ptr @sa_net_dns(ptr)",
    "sa_net_tcp_connect": "declare i64 @sa_net_tcp_connect(ptr, i64, i64)",
    "sa_net_tls_connect": "declare i64 @sa_net_tls_connect(ptr, i64, i64)",
    "sa_net_tcp_listen": "declare i64 @sa_net_tcp_listen(ptr, i64, i64)",
    "sa_net_tcp_accept": "declare i64 @sa_net_tcp_accept(i64, i64)",
    "sa_net_tcp_listener_close": "declare i32 @sa_net_tcp_listener_close(i64)",
    "sa_net_tcp_listener_local_port": "declare i64 @sa_net_tcp_listener_local_port(i64)",
    "sa_net_stream_send": "declare i64 @sa_net_stream_send(i64, ptr)",
    "sa_net_stream_recv": "declare ptr @sa_net_stream_recv(i64, i64)",
    "sa_net_stream_send_buffer": "declare i64 @sa_net_stream_send_buffer(i64, i64, i64, i64)",
    "sa_net_stream_recv_buffer": "declare i64 @sa_net_stream_recv_buffer(i64, i64)",
    "sa_net_stream_close": "declare i32 @sa_net_stream_close(i64)",
    "sa_net_udp_open": "declare i64 @sa_net_udp_open()",
    "sa_net_udp_bind": "declare i32 @sa_net_udp_bind(i64, ptr, i64)",
    "sa_net_udp_connect": "declare i32 @sa_net_udp_connect(i64, ptr, i64)",
    "sa_net_udp_send": "declare i64 @sa_net_udp_send(i64, ptr)",
    "sa_net_udp_send_to": "declare i64 @sa_net_udp_send_to(i64, ptr, i64, ptr)",
    "sa_net_udp_recv": "declare ptr @sa_net_udp_recv(i64, i64)",
    "sa_net_udp_send_buffer": "declare i64 @sa_net_udp_send_buffer(i64, i64, i64, i64)",
    "sa_net_udp_send_buffer_to": "declare i64 @sa_net_udp_send_buffer_to(i64, ptr, i64, i64, i64, i64)",
    "sa_net_udp_recv_buffer": "declare i64 @sa_net_udp_recv_buffer(i64, i64)",
    "sa_net_udp_close": "declare i32 @sa_net_udp_close(i64)",
    "sa_net_udp_local_port": "declare i64 @sa_net_udp_local_port(i64)",
    # BINARY
    "sa_binary_new": "declare i64 @sa_binary_new(i64)",
    # LIST
    "sa_list_new": "declare i64 @sa_list_new()",
    "sa_list_push": "declare i32 @sa_list_push(i64, double)",
    "sa_list_pop": "declare double @sa_list_pop(i64)",
    "sa_list_get": "declare double @sa_list_get(i64, i64)",
    "sa_list_set": "declare i32 @sa_list_set(i64, i64, double)",
    "sa_list_insert": "declare i32 @sa_list_insert(i64, i64, double)",
    "sa_list_remove": "declare i32 @sa_list_remove(i64, i64)",
    "sa_list_length": "declare i64 @sa_list_length(i64)",
    "sa_list_clear": "declare i32 @sa_list_clear(i64)",
    "sa_list_close": "declare i32 @sa_list_close(i64)",
    "sa_strlist_new": "declare i64 @sa_strlist_new()",
    "sa_strlist_push": "declare i32 @sa_strlist_push(i64, ptr)",
    "sa_strlist_pop": "declare ptr @sa_strlist_pop(i64)",
    "sa_strlist_get": "declare ptr @sa_strlist_get(i64, i64)",
    "sa_strlist_set": "declare i32 @sa_strlist_set(i64, i64, ptr)",
    "sa_strlist_insert": "declare i32 @sa_strlist_insert(i64, i64, ptr)",
    "sa_strlist_remove": "declare i32 @sa_strlist_remove(i64, i64)",
    "sa_strlist_length": "declare i64 @sa_strlist_length(i64)",
    "sa_strlist_clear": "declare i32 @sa_strlist_clear(i64)",
    "sa_strlist_close": "declare i32 @sa_strlist_close(i64)",
    "sa_strlist_join": "declare ptr @sa_strlist_join(i64, ptr)",
    "sa_list_last_error_copy": "declare ptr @sa_list_last_error_copy()",
    # MAP
    "sa_map_new": "declare i64 @sa_map_new()",
    "sa_map_set": "declare i32 @sa_map_set(i64, ptr, double)",
    "sa_map_get": "declare double @sa_map_get(i64, ptr)",
    "sa_map_has": "declare i32 @sa_map_has(i64, ptr)",
    "sa_map_remove": "declare i32 @sa_map_remove(i64, ptr)",
    "sa_map_length": "declare i64 @sa_map_length(i64)",
    "sa_map_keys": "declare i64 @sa_map_keys(i64)",
    "sa_map_clear": "declare i32 @sa_map_clear(i64)",
    "sa_map_close": "declare i32 @sa_map_close(i64)",
    "sa_strmap_new": "declare i64 @sa_strmap_new()",
    "sa_strmap_set": "declare i32 @sa_strmap_set(i64, ptr, ptr)",
    "sa_strmap_get": "declare ptr @sa_strmap_get(i64, ptr)",
    "sa_strmap_has": "declare i32 @sa_strmap_has(i64, ptr)",
    "sa_strmap_remove": "declare i32 @sa_strmap_remove(i64, ptr)",
    "sa_strmap_length": "declare i64 @sa_strmap_length(i64)",
    "sa_strmap_keys": "declare i64 @sa_strmap_keys(i64)",
    "sa_strmap_clear": "declare i32 @sa_strmap_clear(i64)",
    "sa_strmap_close": "declare i32 @sa_strmap_close(i64)",
    "sa_map_last_error_copy": "declare ptr @sa_map_last_error_copy()",
    # GUI
    "sa_gui_window": "declare i64 @sa_gui_window(ptr, i64, i64)",
    "sa_gui_button": "declare i64 @sa_gui_button(i64, i64, ptr, i64, i64, i64, i64)",
    "sa_gui_label": "declare i64 @sa_gui_label(i64, ptr, i64, i64, i64, i64)",
    "sa_gui_textbox": "declare i64 @sa_gui_textbox(i64, i64, i64, i64, i64)",
    "sa_gui_set_text": "declare i32 @sa_gui_set_text(i64, ptr)",
    "sa_gui_get_text": "declare ptr @sa_gui_get_text(i64)",
    "sa_gui_wait_event": "declare i64 @sa_gui_wait_event()",
    "sa_gui_close": "declare i32 @sa_gui_close(i64)",
    "sa_gui_last_error_copy": "declare ptr @sa_gui_last_error_copy()",
    "sa_binary_close": "declare i32 @sa_binary_close(i64)",
    "sa_binary_length": "declare i64 @sa_binary_length(i64)",
    "sa_binary_slice": "declare i64 @sa_binary_slice(i64, i64, i64)",
    "sa_binary_copy": "declare i32 @sa_binary_copy(i64, i64, i64, i64, i64)",
    "sa_binary_hex_decode": "declare i64 @sa_binary_hex_decode(ptr)",
    "sa_binary_hex_encode": "declare ptr @sa_binary_hex_encode(i64)",
    "sa_binary_pack_u16_le": "declare i32 @sa_binary_pack_u16_le(i64, i64, i64)",
    "sa_binary_pack_u16_be": "declare i32 @sa_binary_pack_u16_be(i64, i64, i64)",
    "sa_binary_pack_u32_le": "declare i32 @sa_binary_pack_u32_le(i64, i64, i64)",
    "sa_binary_pack_u32_be": "declare i32 @sa_binary_pack_u32_be(i64, i64, i64)",
    "sa_binary_pack_u64_le": "declare i32 @sa_binary_pack_u64_le(i64, i64, i64)",
    "sa_binary_pack_u64_be": "declare i32 @sa_binary_pack_u64_be(i64, i64, i64)",
    "sa_binary_unpack_u16_le": "declare i64 @sa_binary_unpack_u16_le(i64, i64)",
    "sa_binary_unpack_u16_be": "declare i64 @sa_binary_unpack_u16_be(i64, i64)",
    "sa_binary_unpack_u32_le": "declare i64 @sa_binary_unpack_u32_le(i64, i64)",
    "sa_binary_unpack_u32_be": "declare i64 @sa_binary_unpack_u32_be(i64, i64)",
    "sa_binary_unpack_u64_le": "declare i64 @sa_binary_unpack_u64_le(i64, i64)",
    "sa_binary_unpack_u64_be": "declare i64 @sa_binary_unpack_u64_be(i64, i64)",
    "sa_binary_checksum8": "declare i64 @sa_binary_checksum8(i64, i64, i64)",
    "sa_binary_last_error_copy": "declare ptr @sa_binary_last_error_copy()",
    # FILE
    "sa_file_open": "declare i64 @sa_file_open(ptr, ptr)",
    "sa_file_read": "declare ptr @sa_file_read(i64, i64)",
    "sa_file_write": "declare i64 @sa_file_write(i64, ptr)",
    "sa_file_seek": "declare i32 @sa_file_seek(i64, i64, ptr)",
    "sa_file_tell": "declare i64 @sa_file_tell(i64)",
    "sa_file_size": "declare i64 @sa_file_size(i64)",
    "sa_file_close": "declare i32 @sa_file_close(i64)",
    "sa_file_read_text": "declare ptr @sa_file_read_text(ptr)",
    "sa_file_write_text": "declare i32 @sa_file_write_text(ptr, ptr)",
    "sa_file_append_text": "declare i32 @sa_file_append_text(ptr, ptr)",
    "sa_file_exists": "declare i32 @sa_file_exists(ptr)",
    "sa_file_is_file": "declare i32 @sa_file_is_file(ptr)",
    "sa_file_is_dir": "declare i32 @sa_file_is_dir(ptr)",
    "sa_file_delete": "declare i32 @sa_file_delete(ptr)",
    "sa_file_mkdir": "declare i32 @sa_file_mkdir(ptr)",
    "sa_file_cwd": "declare ptr @sa_file_cwd()",
    "sa_file_absolute": "declare ptr @sa_file_absolute(ptr)",
    "sa_file_last_error_copy": "declare ptr @sa_file_last_error_copy()",
    # DESKTOP
    "sa_desktop_message": "declare i32 @sa_desktop_message(ptr, ptr)",
    "sa_desktop_open": "declare i32 @sa_desktop_open(ptr)",
    "sa_desktop_clipboard_set": "declare i32 @sa_desktop_clipboard_set(ptr)",
    "sa_desktop_clipboard_get": "declare ptr @sa_desktop_clipboard_get()",
    "sa_desktop_last_error_copy": "declare ptr @sa_desktop_last_error_copy()",
    "sa_set_string": "declare void @sa_set_string(ptr, ptr)",
    "sa_number": "declare double @sa_number(ptr)",
    "sa_to_string_long": "declare ptr @sa_to_string_long(i64)",
    "sa_to_string_double": "declare ptr @sa_to_string_double(double)",
    "sa_to_string_pointer": "declare ptr @sa_to_string_pointer(ptr)",
    "sa_sb_init": "declare void @sa_sb_init(ptr)",
    "sa_sb_append": "declare void @sa_sb_append(ptr, ptr)",
    "sa_sb_take": "declare ptr @sa_sb_take(ptr)",
    "strcmp": "declare i32 @strcmp(ptr, ptr)",
    # 标准 C
    "free": "declare void @free(ptr)",
    "exit": "declare void @exit(i32)",
    "pow": "declare double @pow(double, double)",
    # SYMBOL
    "sa_symbol_const": "declare ptr @sa_symbol_const(ptr)",
    "sa_symbol_var": "declare ptr @sa_symbol_var(ptr)",
    "sa_symbol_op": "declare ptr @sa_symbol_op(i8, ptr, ptr)",
    "sa_symbol_clone": "declare ptr @sa_symbol_clone(ptr)",
    "sa_symbol_eval": "declare double @sa_symbol_eval(ptr)",
    "sa_symbol_subst": "declare ptr @sa_symbol_subst(ptr, ptr, double)",
    "sa_symbol_deriv": "declare ptr @sa_symbol_deriv(ptr, ptr)",
    "sa_symbol_simplify": "declare ptr @sa_symbol_simplify(ptr)",
    "sa_symbol_free": "declare void @sa_symbol_free(ptr)",
    "sa_symbol_to_string": "declare ptr @sa_symbol_to_string(ptr)",
    # IO
    "sa_read_line": "declare void @sa_read_line(ptr, i64)",
    "sa_cls": "declare void @sa_cls()",
    "sa_setup_console": "declare void @sa_setup_console()",
    # ERROR / TRY-CATCH
    "sa_try_push_env": "declare ptr @sa_try_push_env()",
    "sa_try_pop": "declare void @sa_try_pop()",
    "sa_current_error": "@sa_current_error = external global %SaError",
    "sa_set_error": "declare void @sa_set_error(ptr, ptr)",
    "sa_error_clear": "declare void @sa_error_clear(ptr)",
    "sa_raise_new": "declare void @sa_raise_new(ptr, ptr, i32, ptr)",
    "sa_raise_error": "declare void @sa_raise_error(ptr)",
    "sa_throw_dispatch": "declare void @sa_throw_dispatch()",
    "_setjmp": "declare i32 @_setjmp(ptr, ptr)",
    "llvm.frameaddress": "declare ptr @llvm.frameaddress.p0(i32 immarg)",
}
